//! Marketing-site composites.
//!
//! Scope was set by auditing a real target page (chargewindow-web.fly.dev):
//! hero, feature-card grid, step list, pricing block, cost breakdown, FAQ, and
//! footer. Stable responsive navigation now lives in [`crate::product_shell`].
//! This module has no modal, tab, tooltip or carousel because no page needs one.

use dioxus::prelude::*;

use crate::primitives::StepMarker;

/// One entry in a [`Footer`] column.
#[derive(Debug, Clone, PartialEq)]
pub struct NavItem {
    pub label: String,
    pub href: String,
    /// Opens in a new tab with `rel="noopener noreferrer"`.
    pub external: bool,
}

impl NavItem {
    pub fn new(label: impl Into<String>, href: impl Into<String>) -> Self {
        Self {
            label: label.into(),
            href: href.into(),
            external: false,
        }
    }

    pub fn external(label: impl Into<String>, href: impl Into<String>) -> Self {
        Self {
            label: label.into(),
            href: href.into(),
            external: true,
        }
    }
}

/// Above-the-fold headline block.
///
/// The heading is a literal `<h1>` — a marketing page has exactly one, and it
/// belongs here.
#[component]
pub fn Hero(
    headline: String,
    #[props(default)] subheadline: Option<String>,
    #[props(default)] eyebrow: Option<String>,
    /// Call-to-action row.
    #[props(default)]
    actions: Option<Element>,
    /// Illustration or screenshot, rendered beside the copy on wide screens.
    #[props(default)]
    media: Option<Element>,
) -> Element {
    rsx! {
        div { class: "grid items-center gap-10 lg:grid-cols-2",
            div { class: "flex flex-col gap-5",
                if let Some(eyebrow) = eyebrow {
                    p { class: "text-xs font-medium uppercase tracking-widest text-ink-muted", "{eyebrow}" }
                }
                h1 { class: "text-4xl font-semibold tracking-tight text-ink sm:text-5xl", "{headline}" }
                if let Some(subheadline) = subheadline {
                    p { class: "text-lg text-ink-muted", "{subheadline}" }
                }
                if let Some(actions) = actions {
                    div { class: "flex flex-wrap items-center gap-3 pt-2", {actions} }
                }
            }
            if let Some(media) = media {
                div { class: "flex justify-center lg:justify-end", {media} }
            }
        }
    }
}

/// Numbered card in a feature grid.
#[component]
pub fn FeatureCard(
    title: String,
    body: String,
    #[props(default)] step: Option<u8>,
    /// Trailing link, e.g. an `ArrowLink`.
    #[props(default)]
    action: Option<Element>,
) -> Element {
    rsx! {
        div { class: "flex h-full flex-col gap-3 rounded-lg border border-rule-soft bg-surface p-6",
            if let Some(step) = step {
                StepMarker { n: step }
            }
            h3 { class: "text-base font-semibold text-ink", "{title}" }
            p { class: "flex-1 text-sm text-ink-muted", "{body}" }
            if let Some(action) = action {
                div { class: "pt-1", {action} }
            }
        }
    }
}

/// One step of a numbered process.
#[derive(Debug, Clone, PartialEq)]
pub struct Step {
    pub title: String,
    pub body: String,
}

impl Step {
    pub fn new(title: impl Into<String>, body: impl Into<String>) -> Self {
        Self {
            title: title.into(),
            body: body.into(),
        }
    }
}

/// Ordered "how it works" list.
///
/// A real `<ol>`: the order carries meaning, and the numbers are generated by
/// [`StepMarker`] from the index so they can never drift out of sequence when
/// a step is inserted.
#[component]
pub fn StepList(steps: Vec<Step>) -> Element {
    rsx! {
        ol { class: "flex flex-col gap-6",
            for (index, step) in steps.iter().enumerate() {
                li { class: "flex gap-4",
                    StepMarker { n: (index + 1) as u8 }
                    div { class: "flex flex-col gap-1",
                        h3 { class: "text-base font-semibold text-ink", "{step.title}" }
                        p { class: "text-sm text-ink-muted", "{step.body}" }
                    }
                }
            }
        }
    }
}

/// A `label → value` row, for cost breakdowns and spec tables.
#[derive(Debug, Clone, PartialEq)]
pub struct Fact {
    pub label: String,
    pub value: String,
    /// Renders bold with a top rule — for the total row.
    pub emphasis: bool,
}

impl Fact {
    pub fn new(label: impl Into<String>, value: impl Into<String>) -> Self {
        Self {
            label: label.into(),
            value: value.into(),
            emphasis: false,
        }
    }

    pub fn total(label: impl Into<String>, value: impl Into<String>) -> Self {
        Self {
            label: label.into(),
            value: value.into(),
            emphasis: true,
        }
    }
}

/// Itemised figures.
///
/// A `<dl>` rather than a `<table>`: these are name/value pairs, not tabular
/// data with meaningful rows *and* columns. Values are `tabular-nums` so
/// digits align down the column.
#[component]
pub fn FactList(facts: Vec<Fact>, #[props(default)] class: String) -> Element {
    rsx! {
        dl { class: "flex flex-col gap-2 {class}",
            for fact in facts.iter() {
                div {
                    class: if fact.emphasis {
                        "flex items-baseline justify-between gap-4 border-t border-rule-soft pt-2 font-semibold text-ink"
                    } else {
                        "flex items-baseline justify-between gap-4"
                    },
                    dt { class: "text-sm text-ink-muted", "{fact.label}" }
                    dd { class: "text-sm tabular-nums", "{fact.value}" }
                }
            }
        }
    }
}

/// One-off or subscription price block.
#[component]
pub fn PricingCard(
    price: String,
    #[props(default)] cadence: Option<String>,
    #[props(default)] title: Option<String>,
    #[props(default)] features: Vec<String>,
    #[props(default)] action: Option<Element>,
    #[props(default)] note: Option<String>,
) -> Element {
    rsx! {
        div { class: "flex flex-col gap-5 rounded-lg border border-rule-soft bg-surface p-8",
            if let Some(title) = title {
                h3 { class: "text-base font-semibold text-ink", "{title}" }
            }
            div { class: "flex items-baseline gap-2",
                span { class: "text-4xl font-semibold tracking-tight tabular-nums text-ink", "{price}" }
                if let Some(cadence) = cadence {
                    span { class: "text-sm text-ink-muted", "{cadence}" }
                }
            }
            if !features.is_empty() {
                ul { class: "flex flex-col gap-2",
                    for feature in features.iter() {
                        li { class: "flex items-start gap-2 text-sm text-ink-muted",
                            span { class: "text-ink", "aria-hidden": "true", "✓" }
                            "{feature}"
                        }
                    }
                }
            }
            if let Some(action) = action {
                div { {action} }
            }
            if let Some(note) = note {
                p { class: "text-xs text-ink-muted", "{note}" }
            }
        }
    }
}

/// One question/answer pair.
#[derive(Debug, Clone, PartialEq)]
pub struct QandA {
    pub question: String,
    pub answer: String,
}

impl QandA {
    pub fn new(question: impl Into<String>, answer: impl Into<String>) -> Self {
        Self {
            question: question.into(),
            answer: answer.into(),
        }
    }
}

/// Expandable FAQ list.
///
/// Built on native `<details>`/`<summary>`, which gives correct expand/collapse
/// semantics, keyboard operation and in-page find with **zero JavaScript** —
/// so it works in the SSG build before (or without) hydration. A hand-rolled
/// accordion would need state, an effect, and `aria-expanded` wiring to reach
/// the same place.
#[component]
pub fn Faq(items: Vec<QandA>) -> Element {
    rsx! {
        div { class: "divide-y divide-rule-soft border-y border-rule-soft",
            for item in items.iter() {
                details { class: "group py-4",
                    summary {
                        class: "flex cursor-pointer list-none items-center justify-between gap-4 \
                                text-base font-medium text-ink focus-visible:outline-none \
                                focus-visible:underline",
                        "{item.question}"
                        span {
                            class: "shrink-0 text-ink-faint transition-transform group-open:rotate-45",
                            "aria-hidden": "true",
                            "+"
                        }
                    }
                    p { class: "pt-3 text-sm text-ink-muted", "{item.answer}" }
                }
            }
        }
    }
}

/// A titled column of links in the [`Footer`].
#[derive(Debug, Clone, PartialEq)]
pub struct FooterColumn {
    pub title: String,
    pub items: Vec<NavItem>,
}

impl FooterColumn {
    pub fn new(title: impl Into<String>, items: Vec<NavItem>) -> Self {
        Self {
            title: title.into(),
            items,
        }
    }
}

/// Site footer.
#[component]
pub fn Footer(
    #[props(default)] columns: Vec<FooterColumn>,
    /// Attribution or copyright line.
    #[props(default)]
    note: Option<Element>,
) -> Element {
    rsx! {
        footer { class: "border-t border-rule-soft bg-surface",
            div { class: "mx-auto max-w-5xl px-6 py-12",
                if !columns.is_empty() {
                    div { class: "grid grid-cols-2 gap-8 sm:grid-cols-3 lg:grid-cols-4",
                        for column in columns.iter() {
                            div {
                                h2 { class: "text-xs font-semibold uppercase tracking-widest text-ink-muted",
                                    "{column.title}"
                                }
                                ul { class: "mt-3 flex flex-col gap-2",
                                    for item in column.items.iter() {
                                        li {
                                            a {
                                                class: "text-sm text-ink-muted hover:text-ink",
                                                href: "{item.href}",
                                                target: item.external.then_some("_blank"),
                                                rel: item.external.then_some("noopener noreferrer"),
                                                "{item.label}"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                if let Some(note) = note {
                    div { class: "mt-10 border-t border-rule-soft pt-6 text-xs text-ink-muted", {note} }
                }
            }
        }
    }
}
